import type { FlightResult, ProviderOffer } from "../types/flight";

const airportNames: Record<string, string> = {
  ACC: "Accra",
  ADD: "Addis Ababa",
  ADL: "Adelaide",
  AGA: "Agadir",
  AGP: "Malaga",
  AKL: "Auckland",
  AMM: "Amman",
  ATH: "Athens",
  ATL: "Atlanta",
  AUH: "Abu Dhabi",
  BCN: "Barcelona",
  BEG: "Belgrade",
  BER: "Berlin",
  BKK: "Bangkok",
  BLR: "Bengaluru",
  BOG: "Bogota",
  BOM: "Mumbai",
  BOS: "Boston",
  BSB: "Brasilia",
  BUD: "Budapest",
  BWI: "Baltimore",
  BKI: "Kota Kinabalu",
  BNE: "Brisbane",
  CAN: "Guangzhou",
  CAI: "Cairo",
  CCU: "Kolkata",
  CDG: "Paris",
  CEB: "Cebu",
  CHC: "Christchurch",
  CJU: "Jeju",
  CLO: "Cali",
  CMB: "Colombo",
  CMN: "Casablanca",
  COK: "Kochi",
  CRK: "Clark",
  CTA: "Catania",
  CTG: "Cartagena",
  CTS: "Sapporo",
  CTU: "Chengdu",
  CUN: "Cancun",
  CXR: "Nha Trang",
  DAC: "Dhaka",
  DAD: "Da Nang",
  DAR: "Dar es Salaam",
  DEL: "Delhi",
  DFW: "Dallas",
  DMK: "Bangkok Don Mueang",
  DOH: "Doha",
  DUB: "Dublin",
  DUS: "Dusseldorf",
  DUR: "Durban",
  DVO: "Davao",
  DXB: "Dubai",
  EDI: "Edinburgh",
  EIN: "Eindhoven",
  EWR: "Newark",
  EZE: "Buenos Aires",
  FAO: "Faro",
  FCO: "Rome",
  FRA: "Frankfurt",
  FUK: "Fukuoka",
  GIG: "Rio de Janeiro",
  GDL: "Guadalajara",
  GMP: "Seoul Gimpo",
  GOI: "Goa",
  GRU: "Sao Paulo",
  HAM: "Hamburg",
  HAN: "Hanoi",
  HKG: "Hong Kong",
  HKT: "Phuket",
  HND: "Tokyo Haneda",
  HRG: "Hurghada",
  HYD: "Hyderabad",
  IAD: "Washington Dulles",
  ICN: "Seoul Incheon",
  IST: "Istanbul",
  JED: "Jeddah",
  JFK: "New York",
  JNB: "Johannesburg",
  KBV: "Krabi",
  KEF: "Reykjavik",
  KHH: "Kaohsiung",
  KIX: "Osaka",
  KNO: "Medan",
  KUL: "Kuala Lumpur",
  KWI: "Kuwait City",
  LGK: "Langkawi",
  LGW: "London Gatwick",
  LHR: "London Heathrow",
  LIM: "Lima",
  LIS: "Lisbon",
  LOS: "Lagos",
  LYS: "Lyon",
  MAA: "Chennai",
  MAD: "Madrid",
  MAN: "Manchester",
  MBA: "Mombasa",
  MDE: "Medellin",
  MEL: "Melbourne",
  MEX: "Mexico City",
  MIA: "Miami",
  MNL: "Manila",
  MRS: "Marseille",
  MUC: "Munich",
  MCT: "Muscat",
  MTY: "Monterrey",
  MXP: "Milan",
  NAN: "Nadi",
  NAP: "Naples",
  NBO: "Nairobi",
  NCE: "Nice",
  NGO: "Nagoya",
  NRT: "Tokyo Narita",
  OOL: "Gold Coast",
  OPO: "Porto",
  ORY: "Paris Orly",
  OTP: "Bucharest",
  PEK: "Beijing Capital",
  PEN: "Penang",
  PER: "Perth",
  PKX: "Beijing Daxing",
  PMI: "Palma de Mallorca",
  PRG: "Prague",
  PTY: "Panama City",
  PUS: "Busan",
  PVR: "Puerto Vallarta",
  PVG: "Shanghai",
  PQC: "Phu Quoc",
  RAK: "Marrakesh",
  RIX: "Riga",
  RTM: "Rotterdam",
  RUH: "Riyadh",
  SAW: "Istanbul Sabiha Gokcen",
  SCL: "Santiago",
  SFO: "San Francisco",
  SGN: "Ho Chi Minh City",
  SHJ: "Sharjah",
  SIN: "Singapore",
  SJO: "San Jose",
  SOF: "Sofia",
  SSH: "Sharm El Sheikh",
  SUB: "Surabaya",
  SVQ: "Seville",
  SYD: "Sydney",
  SZX: "Shenzhen",
  TSA: "Taipei Songshan",
  TBS: "Tbilisi",
  TPE: "Taipei",
  UPG: "Makassar",
  VCE: "Venice",
  VIE: "Vienna",
  WAW: "Warsaw",
  WLG: "Wellington",
  XIY: "Xi'an",
  YEG: "Edmonton",
  YOW: "Ottawa",
  YUL: "Montreal",
  YVR: "Vancouver",
  YYC: "Calgary",
  YYZ: "Toronto",
  ZQN: "Queenstown",
  ZRH: "Zurich",
};

const airlineNames: Record<string, string> = {
  AC: "Air Canada",
  AF: "Air France",
  AM: "Aeromexico",
  AV: "Avianca",
  BA: "British Airways",
  CM: "Copa Airlines",
  DL: "Delta Air Lines",
  FI: "Icelandair",
  IB: "Iberia",
  KL: "KLM",
  LH: "Lufthansa",
  TK: "Turkish Airlines",
  TP: "TAP Air Portugal",
  TS: "Air Transat",
  UA: "United Airlines",
  WS: "WestJet",
};

export function normalizeOffers(offers: ProviderOffer[]): FlightResult[] {
  return offers.map((offer) => {
    const price = Number(offer.amount);

    return {
      destination: offer.destinationName ?? airportNames[offer.destinationCode] ?? offer.destinationCode,
      destinationCode: offer.destinationCode,
      price: Number.isFinite(price) ? price : 0,
      currency: offer.currency,
      departDate: offer.departDate,
      returnDate: offer.returnDate,
      stops: offer.stops,
      airlineCode: offer.airlineCode,
      airlineName: offer.airlineName ?? (offer.airlineCode ? airlineNames[offer.airlineCode] : undefined),
      lastVerifiedAt: offer.lastVerifiedAt,
      bookingLink: offer.bookingLink,
      googleFlightsLink: offer.googleFlightsLink,
    };
  });
}
